version: '3.8'

services:
  go-api:
    build: .
    container_name: go-api
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped
    network_mode: "bridge"
